site_name: Anime song CD release date list

# Repository
repo_name: onihusube/songcalendartest
repo_url: https://github.com/onihusube/songcalendartest
edit_uri: ""

# Theme
theme:
  name: 'material'
  language: 'ja'
  # favicon: 'assets/images/logo.png'
  logo:
    icon: 'queue_music'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: true
extra:
  search:
    language: 'en, ja'
    tokenizer: '[\sã€€ã€ã€‚ï¼Œï¼ãƒ»ï½&!?ï¼ï¼Ÿã¯ãŒã®ã‚’ã«ã¸ã¨ã§ã‚„ã‹ã‚‚ã‚‹ã€Œã€ã€ã€]+'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/onihusube9'
google_analytics:
  - 'UA-150909325-1'
  - 'auto'

# Page tree
nav:
  - Home:
    - ğŸ¡ãƒˆãƒƒãƒ—ãƒšãƒ¼ã‚¸ : index.md
    - ğŸ“–ã“ã®ã‚µã‚¤ãƒˆã®è¦‹æ–¹ : å‡¡ä¾‹.md
  - 2019:
    - 1æœˆğŸ: 2019/1æœˆåˆ†.md
    - 2æœˆğŸ‘¹: 2019/2æœˆåˆ†.md
    - 3æœˆğŸ: 2019/3æœˆåˆ†.md
    - 4æœˆğŸŒ¸: 2019/4æœˆåˆ†.md
    - 5æœˆğŸ: 2019/5æœˆåˆ†.md
    - 6æœˆâ˜”ï¸: 2019/6æœˆåˆ†.md
    - 7æœˆğŸ‹: 2019/7æœˆåˆ†.md
    - 8æœˆğŸ†: 2019/8æœˆåˆ†.md
    - 9æœˆğŸ‘: 2019/9æœˆåˆ†.md
  - 2018:
    - 12æœˆğŸ„: 2018/12æœˆåˆ†.md
