site_name: Anime song CD release date list

# Repository
repo_name: onihusube/songcalendartest
repo_url: https://github.com/onihusube/songcalendartest
edit_uri: ""

# Theme
theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: true
extra:
  search:
    language: 'en, ja'
    tokenizer: '[\sã€€ã€ã€‚ï¼Œï¼ãƒ»ï½]+'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/onihusube9'

# Page tree
nav:
  - Home: index.md
  - 2019:
    - ğŸ1æœˆ: 2019/1æœˆåˆ†.md
    - ğŸ‘¹2æœˆ: 2019/2æœˆåˆ†.md
    - ğŸ3æœˆ: 2019/3æœˆåˆ†.md
    - ğŸŒ¸4æœˆ: 2019/4æœˆåˆ†.md
    - ğŸ5æœˆ: 2019/5æœˆåˆ†.md
    - â˜”ï¸6æœˆ: 2019/6æœˆåˆ†.md
    - ğŸ‹7æœˆ: 2019/7æœˆåˆ†.md
    - ğŸ†8æœˆ: 2019/8æœˆåˆ†.md
    - ğŸ‘9æœˆ: 2019/9æœˆåˆ†.md
  - 2018:
    - ğŸ„12æœˆ: 2018/12æœˆåˆ†.md
